<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PublicPageSetting extends Model
{
    protected $fillable = ['content'];

    protected $casts = [
        'content' => 'array',
    ];

    public static function othersDefaults(): array
    {
        return [
            'contact' => [
                'location_label' => 'Our Location',
                'location_text' => 'Barangay Maroyroy, Macatoc, Oriental Mindoro, Luzon Philippines',
                'phone_label' => 'Phone Number',
                'phone_text' => '',
                'email_label' => 'Email Address',
                'email_text' => 'jmcasabar@gmail.com',
                'facebook_label' => 'Facebook Account',
                'facebook_text' => 'facebook.com/share/18gxfPvdFU',
                'facebook_url' => 'https://www.facebook.com/share/18gxfPvdFU/',
            ],
            'about' => [
                'story_title' => 'Our Story',
                'story_p1' => 'Founded in 2010, Mr. Casabar started his own business, one of it are the JM Casabar Mini Farm, which has been at the forefront of sustainable duck, chicken, hog, turkey, and rabbit farming and premium poultry products. What began as a small family farm has grown into a trusted supplier of high-quality goods such as meat, eggs, and related products.',
                'story_p2' => 'We take pride in our commitment to ethical farming practices and maintaining the highest standards of quality in all our products. Our dedication to sustainability and animal welfare has made us a leader in the industry, trusted by chefs and home cooks alike.',
                'card1_title' => 'Quality First',
                'card1_text' => 'We never compromise on the quality of our products and services, ensuring that every item meets our rigorous standards.',
                'card2_title' => 'Sustainability',
                'card2_text' => 'Committed to environmental responsibility and sustainable farming practices, we strive to minimize our ecological footprint.',
                'card3_title' => 'Community',
                'card3_text' => 'Supporting local communities and maintaining strong relationships with our customers is at the heart of everything we do.',
            ],
            'faq' => [
                'hero_title' => 'Frequently Asked Questions',
                'hero_subtitle' => 'Find answers to common questions about JM Casabar Private Farm',
                'search_placeholder' => 'Search questions...',
                'stat_1_number' => '24/7',
                'stat_1_label' => 'Online Support',
                'stat_2_number' => '1000+',
                'stat_2_label' => 'Happy Customers',
                'stat_3_number' => '5★',
                'stat_3_label' => 'Customer Rating',
                'stat_4_number' => '50+',
                'stat_4_label' => 'Questions Answered',
                'general_title' => 'General Farm & Ordering Information',
                'general_subtitle' => 'Everything you need to know about ordering and our farm',
                'general_q1' => 'Where is JM Casabar Private Farm located?',
                'general_a1' => 'JM Casabar Private Farm is located in Brgy. Maroyroy, Macatoc, Victoria, Mimaropa, Philippines. Our farm is easily accessible and we provide detailed directions with every order confirmation.',
                'general_q2' => 'What are your operating hours for online orders?',
                'general_a2' => 'Our online store is open 24/7 for placing orders. Processing and delivery schedules will be specified during checkout and in your order confirmation email.',
                'general_q3' => 'What payment methods do you accept?',
                'general_a3' => "Digital Payments:\n- GCash\n- PayMaya\n\nTraditional Methods:\n- Cash on Delivery (COD)\n- Online Payments",
                'general_q4' => 'Do you offer discounts for bulk orders?',
                'general_a4' => "Yes! We offer attractive discounts for bulk orders.\n\nBulk Pricing Applies To:\n- Orders of 10+ items\n- Orders exceeding ₱5,000\n- Custom quotes available",
                'general_q5' => 'How do I know my order has been confirmed?',
                'general_a5' => "You will receive both Gmail and SMS confirmation once your order has been successfully placed and payment verified.\n\nYour confirmation includes:\n- Order number\n- Estimated delivery time\n- Tracking information\n- Contact details",
                'wine_title' => 'Macopa Wine',
                'wine_subtitle' => 'Learn about our artisanal macopa wine',
                'wine_q1' => 'What is JM Casabar Private Farm Macopa Wine?',
                'wine_a1' => 'Our macopa wine is an artisanal fruit wine crafted exclusively from ripe macopa fruit ("Malay apple" or Syzygium samarangense) harvested from our private farm.',
                'wine_q2' => 'How should I store macopa wine?',
                'wine_a2' => "Optimal Storage Conditions:\n- Temperature: 10-15°C (50-59°F)\n- Location: Cool, dark place\n- Position: Store horizontally if cork-sealed\n- Environment: Away from direct sunlight and strong odors",
                'wine_q3' => 'Do you sell to minors?',
                'wine_a3' => 'No. As per Philippine law, we strictly do not sell alcoholic beverages to individuals under 18 years old. Age verification may be required upon delivery.',
                'duck_title' => 'Duck Products',
                'duck_subtitle' => 'Fresh duck meat and eggs from our ethically raised Pekin ducks',
                'duck_q1' => 'What types of duck products do you offer?',
                'duck_a1' => "Fresh Duck Meat:\n- Whole dressed duck\n- Duck breast\n- Duck legs\n- Duck wings\n\nDuck Eggs:\n- Fresh duck eggs\n- Salted duck eggs\n- Balut\n- Penoy",
                'duck_q2' => 'Are your ducks raised ethically?',
                'duck_a2' => "Yes! Our Pekin ducks are ethically raised in spacious environments.\n\nOur Ethical Practices:\n- Spacious, clean living environments\n- Access to natural foraging areas\n- Clean, fresh water supply\n- Regular veterinary care\n- Stress-free handling procedures",
                'incubation_title' => 'Incubation Services',
                'incubation_subtitle' => 'Professional egg incubation with modern equipment',
                'incubation_q1' => 'What incubation services do you offer?',
                'incubation_a1' => "We provide professional incubation services for duck eggs and chicken eggs.\n\nOur Equipment:\n- Modern, reliable incubators\n- Controlled environment\n- Optimal conditions throughout incubation\n- Professional monitoring",
                'incubation_q2' => 'How long does the incubation process take?',
                'incubation_a2' => "Duck eggs: approximately 28 days\nChicken eggs: approximately 21 days",
                'cta_title' => 'Still Have Questions?',
                'cta_subtitle' => "Can't find the answer you're looking for? Our friendly customer support team is here to help you 24/7.",
                'cta_button_contact' => 'Contact Support',
                'cta_button_call' => 'Call Us Now',
                'cta_bottom_note' => 'Average response time: 2 hours | Customer satisfaction: 98%',
            ],
            'privacy' => [
                'hero_title' => 'Privacy Policy',
                'hero_subtitle' => 'Your privacy is important to us',
                'dpa_title' => 'Data Privacy Act Compliance',
                'dpa_text' => 'This Privacy Policy is designed to comply with the Data Privacy Act of 2012 (Republic Act No. 10173) and its Implementing Rules and Regulations.',
                'overview_title' => 'Overview',
                'overview_subtitle' => 'Understanding our commitment to your privacy',
                'overview_text' => 'JM Casabar Private Farm ("we," "our," or "us") respects your privacy and is committed to protecting your personal data.',
                'company_name' => 'JM Casabar Pekin Store (JM Casabar Mini Farm)',
                'company_address' => 'Brgy. Maroyroy, Macatoc, Oriental Mindoro, Luzon, Philippines',
                'company_contact' => '',
                'company_dpo' => 'Please contact us at jmcasabar@gmail.com',
                'collect_title' => 'Information We Collect',
                'collect_subtitle' => 'Types of personal data we may collect from you',
                'collect_personal' => "Full name\nEmail address\nPhone number\nMailing address\nDate of birth (for age verification)",
                'collect_transaction' => "Order history\nPayment information\nDelivery preferences\nProduct preferences\nCommunication records",
                'collect_technical' => "IP address\nBrowser type and version\nDevice information\nUsage data\nCookies and tracking data",
                'collect_communication' => "Customer service inquiries\nFeedback and reviews\nSurvey responses\nMarketing preferences\nSocial media interactions",
                'use_title' => 'How We Use Your Information',
                'use_subtitle' => 'Lawful purposes for processing your personal data',
                'use_1_title' => 'Order Processing and Fulfillment',
                'use_1_text' => 'To process your orders, arrange delivery, handle payments, and provide customer support.',
                'use_2_title' => 'Communication',
                'use_2_text' => 'To send order confirmations, delivery updates, respond to inquiries, and provide important notices.',
                'use_3_title' => 'Marketing and Promotions',
                'use_3_text' => 'To send promotional materials, special offers, and newsletters (with your consent).',
                'use_4_title' => 'Legal Compliance',
                'use_4_text' => 'To comply with legal obligations, including tax requirements and regulatory compliance.',
                'use_5_title' => 'Business Operations',
                'use_5_text' => 'To improve our services, conduct analytics, prevent fraud, and ensure website security.',
                'share_title' => 'Information Sharing and Disclosure',
                'share_subtitle' => 'When and how we may share your information',
                'share_notice' => 'We do not sell, trade, or rent your personal information to third parties for their marketing purposes.',
                'share_1_title' => 'Service Providers',
                'share_1_text' => 'We may share information with trusted third-party providers who assist us in operating our business.',
                'share_2_title' => 'Legal Requirements',
                'share_2_text' => 'We may disclose information when required by law or to protect our rights and safety.',
                'share_3_title' => 'Business Transfers',
                'share_3_text' => 'In the event of a merger, acquisition, or sale of assets, your information may be transferred.',
                'security_title' => 'Data Security',
                'security_subtitle' => 'How we protect your personal information',
                'security_intro' => 'We implement appropriate technical and organizational security measures to protect your personal data.',
                'security_technical' => "SSL encryption for data transmission\nSecure servers and databases\nRegular security updates\nFirewall protection\nAccess controls and authentication",
                'security_org' => "Staff training on data protection\nLimited access on need-to-know basis\nRegular security assessments\nData breach response procedures\nConfidentiality agreements",
                'rights_title' => 'Your Rights Under the Data Privacy Act',
                'rights_subtitle' => 'Your rights as a data subject in the Philippines',
                'rights_1_title' => 'Right to be Informed',
                'rights_1_text' => 'You have the right to know how your personal data is being processed.',
                'rights_2_title' => 'Right to Access',
                'rights_2_text' => 'You can request access to your personal data that we hold.',
                'rights_3_title' => 'Right to Rectification',
                'rights_3_text' => 'You can request correction of inaccurate or incomplete personal data.',
                'rights_4_title' => 'Right to Erasure',
                'rights_4_text' => 'You can request deletion of your personal data under certain circumstances.',
                'rights_5_title' => 'Right to Object',
                'rights_5_text' => 'You can object to the processing of your personal data for certain purposes.',
                'rights_6_title' => 'Right to Data Portability',
                'rights_6_text' => 'You can request your personal data in a structured, commonly used format.',
                'rights_7_title' => 'Right to Restrict Processing',
                'rights_7_text' => 'You can request limitation of processing under certain conditions.',
                'rights_8_title' => 'Right to File Complaints',
                'rights_8_text' => 'You can file complaints with the National Privacy Commission.',
                'rights_how' => 'To exercise any of these rights, please contact us using the information provided in the Contact section below.',
                'rights_note' => 'Some rights may be subject to certain conditions and exceptions as provided by law.',
                'cookies_title' => 'Cookies and Tracking Technologies',
                'cookies_subtitle' => 'How we use cookies and similar technologies',
                'cookies_intro' => 'We use cookies and similar tracking technologies to enhance your browsing experience, analyze website traffic, and personalize content.',
                'cookies_1_title' => 'Essential Cookies',
                'cookies_1_text' => 'Required for website functionality and security.',
                'cookies_2_title' => 'Analytics Cookies',
                'cookies_2_text' => 'Help us understand how visitors use our website.',
                'cookies_3_title' => 'Marketing Cookies',
                'cookies_3_text' => 'Used to deliver relevant advertisements and track campaigns.',
                'retention_title' => 'Data Retention',
                'retention_subtitle' => 'How long we keep your personal information',
                'retention_intro' => 'We retain your personal data only for as long as necessary to fulfill the purposes for which it was collected.',
                'retention_1_title' => 'Account Information',
                'retention_1_text' => 'Retained while your account is active and for 7 years after account closure.',
                'retention_2_title' => 'Transaction Records',
                'retention_2_text' => 'Retained for 10 years as required by law.',
                'retention_3_title' => 'Marketing Communications',
                'retention_3_text' => 'Retained until you unsubscribe or withdraw consent.',
                'contact_title' => 'Contact Us',
                'contact_subtitle' => 'Get in touch regarding privacy matters',
                'contact_intro' => 'If you have questions about this Privacy Policy or wish to exercise your rights, please contact us.',
                'contact_company_title' => 'JM Casabar Private Farm',
                'contact_company_address' => 'Brgy. Maroyroy, Macatoc, Victoria, Oriental Mindoro',
                'contact_company_phone' => '',
                'contact_company_email' => 'jmcasabar@gmail.com',
                'contact_npc_title' => 'National Privacy Commission',
                'contact_npc_text' => 'If you believe we have violated your privacy rights, you may file a complaint with:',
                'contact_npc_web' => 'www.privacy.gov.ph',
                'contact_npc_email' => 'info@privacy.gov.ph',
                'updates_title' => 'Policy Updates',
                'updates_subtitle' => 'How we handle changes to this privacy policy',
                'updates_intro' => 'We may update this Privacy Policy from time to time to reflect changes in our practices, technology, legal requirements, or other factors.',
                'updates_email_title' => 'Email Notification',
                'updates_email_text' => 'Sending notice to your registered email address.',
                'updates_site_title' => 'Website Notice',
                'updates_site_text' => 'Posting a prominent notice on our website.',
                'updates_note' => 'Your continued use of our services after the effective date of any changes constitutes your acceptance of the revised Privacy Policy.',
                'footer_title' => 'Your Privacy Matters',
                'footer_subtitle' => 'We are committed to protecting your personal data and respecting your privacy rights under Philippine law.',
                'footer_btn_1' => 'Contact Our Privacy Team',
                'footer_btn_2' => 'Return to Home',
            ],
        ];
    }

    public static function defaults(): array
    {
        return [
            'store_name' => 'JM Casabar Mini Farm',
            'store_logo' => 'images/fav-icon.png',
            'hero_title' => 'Farm-Fresh Pekin Duck Products',
            'hero_subtitle' => 'Experience the exceptional quality of our farm-raised Pekin ducks. From premium meat cuts to fresh eggs, we offer the finest duck products straight from our family farm to your table.',
            'hero_image' => 'images/pekin-young-alive.jpg',
            'about_title' => 'Our Mission & Story',
            'about_paragraph_1' => "At JM Casabar Mini Farm, we're dedicated to raising the healthiest, happiest Pekin ducks using sustainable and ethical farming practices. Our family-owned farm has been in operation for over 15 years, focusing on quality over quantity.",
            'about_paragraph_2' => "We believe that happy ducks produce the best meat and eggs. That's why our ducks enjoy spacious, clean living conditions with access to fresh water and natural feed. We never use antibiotics or growth hormones, ensuring you get the purest duck products possible.",
            'about_paragraph_3' => "From our farm to your table, we take pride in offering premium duck products that are not only delicious but also responsibly raised. Whether you're a chef looking for the finest ingredients or a home cook wanting to try something special, our duck products will exceed your expectations.",
            'about_image' => 'images/Male_Pekin_Duck.jpg',
            'stat_1_number' => '100%',
            'stat_1_label' => 'Natural Feed',
            'stat_2_number' => '15+',
            'stat_2_label' => 'Years Experience',
            'stat_3_number' => '0',
            'stat_3_label' => 'Antibiotics Used',
            'stat_4_number' => '1000+',
            'stat_4_label' => 'Happy Customers',
            'features_title' => 'Why Choose Our Duck Products?',
            'features_subtitle' => 'We take pride in offering the highest quality Pekin duck products, raised with care and processed with attention to detail.',
            'feature_1_title' => '100% Natural',
            'feature_1_text' => 'Our ducks are raised naturally without antibiotics or growth hormones.',
            'feature_2_title' => 'Premium Quality',
            'feature_2_text' => 'Each product meets our strict quality standards before reaching your table.',
            'feature_3_title' => 'Fast Delivery',
            'feature_3_text' => 'We ensure quick and safe delivery to maintain freshness and quality.',
            'feature_4_title' => 'Ethically Raised',
            'feature_4_text' => 'Our ducks enjoy spacious, clean living conditions with proper care.',
            'footer_brand_name' => 'Flappy-Beak',
            'footer_brand_text' => 'Premium farm-raised Pekin duck products delivered straight to your door.',
            'contact_address' => 'Brgy. Maroyroy, Macatoc, Oriental Mindoro, Luzon Philippines',
            'contact_email' => 'jmcasabar@gmail.com',
            'business_hours_1' => 'Monday - Friday: 8am - 5pm',
            'business_hours_2' => 'Saturday: 9am - 4pm',
            'business_hours_3' => 'Sunday: Closed',
            'others' => static::othersDefaults(),
        ];
    }

    public static function getContent(): array
    {
        $row = static::query()->first();
        $merged = array_replace_recursive(static::defaults(), $row?->content ?? []);
        $merged['others'] = array_replace_recursive(static::othersDefaults(), $row?->content['others'] ?? []);

        return $merged;
    }
}
